version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: auth_micro
    environment:
      POSTGRES_DB: auth_micro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3.9.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  postgres-data:
  rabbitmq_data:
